<style media="screen">
  .price-range-form{
    margin-bottom: 20px;
  }
  .price-range-form .field{
    display: inline-block;
  }
  .price-range-form .form-submit{
    display: inline-block;
  }
  .render-table table > thead > tr > th, .render-table table > tbody > tr > td{
    border: 1px solid;
  }
</style>

<!-- Form -->
<form class="price-range-form" data-mage-init='{
  "validation": {
    "rules": {
      "min-price": {
        "required": true,
        "validate-greater-than-zero": true

      },
      "max-price": {
        "required": true,
        "validate-greater-than-zero": true,
        "validate-number-range": true

      }
    }
}}' method="post">
  <div class="field">
    <label for="min-price">
      <span><?php echo __('Minimum Price') ?></span>
    </label>
    <input id="min-price" type="text" name="min-price">
  </div>
  <div class="field">
    <label for="max-price">
      <span><?php echo __('Maximum Price') ?></span>
    </label>
    <input id="max-price" type="text" name="max-price">
  </div>
  <div class="field">
    <label for="sort-by">
      <span><?php echo __('Sort By') ?></span>
    </label>
    <select class="" name="sort-by">
      <option value="asc"><?php echo __('Asc') ?></option>
      <option value="desc"><?php echo __('Desc') ?></option>
    </select>
  </div>
  <div class="form-submit">
    <button type="submit" name="button"><?php echo __('Search') ?></button>
  </div>
</form>
<!-- End Form -->

<!-- When search result 0 -->
<div class="none-message" style="display: none;">
  <p style="color: red;">No products within this price range.</p>
</div>

<!-- Backend Validation Error Message -->
<div class="error-message" style="display: none;">
  <p style="color: red;">Oops, backend validation failed.</p>
</div>

<!-- Product Table -->
<div class="render-table" style="display: none;">
  <table>
      <thead>
        <tr>
          <th class="col"><?php echo __("Thumbnail");?></th>
          <th class="col"><?php echo __("SKU");?></th>
          <th class="col"><?php echo __("Name");?></th>
          <th class="col"><?php echo __("Qty");?></th>
          <th class="col"><?php echo __("Price");?></th>
          <th class="col"><?php echo __("Link");?></th>
        </tr>
      </thead>

      <tbody>
        <!-- Body Content Append by JS -->
      </tbody>
  </table>
</div>
<!-- End Product Table -->

<script type="text/javascript">
  require([
    // Require Library
    'jquery',
    'mage/validation'
  ], function($){
    $('.price-range-form').submit(function(event){
      event.preventDefault();
      var formValidation = $('.price-range-form').validation('isValid');

      if (formValidation) {
        event.preventDefault();

        // AJAX Begin
        $.ajax({
          url: "<?= $block->getSubmitUrl(); ?>",
          type: 'POST',
          data: $(this).serialize(),
          showLoader: true
        }).done(function(responses){
          // Callback
          if(responses.length > 0){
            $('.error-message, .none-message').hide();
            $('.render-table').show();

            // Construct Product Table
            var productTemplate = '';
            $.each(responses, function(i, product){
              productTemplate += '<tr>';
              productTemplate += '<td style="max-width: 100px;">' + '<img src="' + product.thumbnail + '">' + '</td>';
              productTemplate += '<td>' + product.sku + '</td>';
              productTemplate += '<td>' + product.name + '</td>';
              productTemplate += '<td>' + product.qty + '</td>';
              productTemplate += '<td>' + product.price + '</td>';
              productTemplate += '<td>' + '<a href="' + product.url + '" target="_blank">' + "Open" + '</a>' + '</td>';
              productTemplate += '</tr>';
            })
            $('.render-table table tbody').empty().append(productTemplate);

          }else{
            // When No Returned Results
            $('.render-table').hide();
            $('.none-message').show();
          }
        });
      }else{
        // Frontend Validation Failed
        $('.render-table table tbody').empty();
        $('.render-table').hide();
      }

    });
  })
</script>
